"""Configuration loader for the first-phase TOML shape."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from db_lens_mcp.errors import ConfigurationError
from db_lens_mcp.infrastructure.config.config_models import AppConfig, ProfileConfig


DEFAULT_CONFIG_PATH = Path.home() / ".db-lens" / "config.toml"
CONFIG_FILE_ENV = "DB_LENS_CONFIG_FILE"


def resolve_config_path(path: Path | None = None) -> Path:
    """Resolve config path from explicit path, environment, or default."""

    if path is not None:
        return path
    env_path = os.getenv(CONFIG_FILE_ENV)
    if env_path:
        return Path(env_path).expanduser()
    return DEFAULT_CONFIG_PATH


class ConfigLoader:
    """Load db-lens-mcp TOML configuration."""

    def load(self, path: Path | None = None) -> AppConfig:
        """Load configuration from TOML."""

        config_path = resolve_config_path(path)
        if not config_path.exists():
            raise ConfigurationError(f"Configuration file does not exist: {config_path}")
        try:
            return AppConfig(**_load_toml(config_path))
        except ConfigurationError:
            raise
        except Exception as exc:
            raise ConfigurationError(f"Invalid configuration file: {config_path}") from exc

    def save(self, config: AppConfig, path: Path | None = None) -> Path:
        """Save configuration to TOML using the project fixed shape."""

        config_path = resolve_config_path(path)
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(_dump_config(config), encoding="utf-8")
        try:
            config_path.chmod(0o600)
        except PermissionError:
            # Some filesystems do not support chmod. Doctor reports this later.
            pass
        return config_path

    def exists(self, path: Path | None = None) -> bool:
        """Return whether the resolved config file exists."""

        return resolve_config_path(path).exists()


def _load_toml(path: Path) -> dict[str, Any]:
    """Load TOML with stdlib when available, otherwise parse the fixed shape."""

    try:
        import tomllib
    except ModuleNotFoundError:
        return _load_fixed_toml(path)
    with path.open("rb") as config_file:
        return tomllib.load(config_file)


def _load_fixed_toml(path: Path) -> dict[str, Any]:
    """Parse the TOML subset generated by `_dump_config`.

    This fallback exists so repository tests can run on older local Python
    versions. The product target remains Python 3.11+.
    """

    data: dict[str, Any] = {"profiles": {}}
    current_profile: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[profiles.") and line.endswith("]"):
            current_profile = line[len("[profiles.") : -1]
            data["profiles"][current_profile] = {}
            continue
        if "=" not in line:
            raise ConfigurationError(f"Unsupported config line: {raw_line}")
        key, raw_value = [part.strip() for part in line.split("=", 1)]
        value = _parse_value(raw_value)
        if current_profile is None:
            data[key] = value
        else:
            data["profiles"][current_profile][key] = value
    return data


def _parse_value(raw_value: str) -> Any:
    if raw_value.startswith('"') and raw_value.endswith('"'):
        return raw_value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    try:
        return int(raw_value)
    except ValueError:
        return raw_value


def _dump_config(config: AppConfig) -> str:
    lines: list[str] = []
    if config.default_profile:
        lines.append(f'default_profile = "{_escape(config.default_profile)}"')
        lines.append("")
    for name in sorted(config.profiles):
        profile = config.profiles[name]
        lines.append(f"[profiles.{_escape(name)}]")
        lines.extend(_dump_profile(profile))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _dump_profile(profile: ProfileConfig) -> list[str]:
    return [
        f'driver = "{_escape(profile.driver)}"',
        f'host = "{_escape(profile.host)}"',
        f"port = {profile.port}",
        f'database = "{_escape(profile.database)}"',
        f'username = "{_escape(profile.username)}"',
        f'password = "{_escape(profile.password)}"',
        f"connect_timeout_seconds = {profile.connect_timeout_seconds}",
        f"read_timeout_seconds = {profile.read_timeout_seconds}",
    ]


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
